export const type = {
    // Auth
    LOGIN: '[AUTH] LOGIN',
    LOGOUT: '[AUTH] LOGOUT',

    // DONACION
    SET_ALL_DONACIONES: '[SET ALL] ',
    GET_ALL_DONACIONES: '[GET ALL] DONACIONES',
    GET_DONACION: '[GET] DONACION',
    CREATE_DONACION: '[POST] DONACION',
    EDIT_DONACION: '[PATCH] DONACION',
    DELETE_DONACION: '[DELETE] DONACION'
    
}